# First Post
This is the first post and the last blog you will ever want to read

In [1]:
import numpy as np

In [2]:
vector = np.array([1,2,3])
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
print(vector * matrix)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
